local_costmap:
  global_frame: /map
  robot_base_frame: base_link
  update_frequency: 50.0
  publish_frequency: 30.0
  static_map: true
  rolling_window: true
  width: 5.0
  height: 5.0
  resolution: 0.05
  origin_x: -7.0
  origin_y: -7.0
