TrajectoryPlannerROS:
  max_vel_x: 0.4
  min_vel_x: 0.1
  max_vel_theta: 0.9
  min_vel_theta: -0.9
  min_in_place_vel_theta: 0.2

  acc_lim_theta: 0.7
  acc_lim_x: 0.1
  acc_lim_y: 0.1

  holonomic_robot: true
  meter_scoring: true
